# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS python workflow
on:
  push:
    branches: "main"
env:
  LAMBDA_NAME : "my_func_counter"
  AWS_REGION : "us-west-1"
#  permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::211125468825:role/github-cicd
          role-session-name: aws_backend_workflow
          aws-region: ${{ env.AWS_REGION }}

      #Zip the .py file 
      - name: Create Zip archive
        run: |
          if [[ ! -f ./infra/lambda/my_func_counter.zip ]]; then
            zip -j ./infra/lambda/my_func_counter.zip ./infra/lambda/func.py
          fi
          
      # Upload a file to AWS Lambda
      - name:  Copy func.zip to Lambda
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --zip-file fileb://infra/lambda/my_func_counter.zip
      
      #Remove temporary zip file
      - name: Remove zip file
        run: |
          rm -f ./infra/lambda/my_func_counter.zip